
FROM node:18-alpine

WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

RUN npm install

COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Start the application
CMD ["node", "server.js"]