# syntax=docker/dockerfile:1

FROM node:18-alpine

WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./


RUN npm install

COPY . .

# Start the application
CMD ["node", "server.js"]